# Generated by Django 4.2.10 on 2024-06-29 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_delete_custommatch'),
        ('custommatches', '0002_alter_custommatch_is_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_userteam', models.IntegerField()),
                ('score_versusteam', models.IntegerField(verbose_name='Opposition Score?')),
                ('custom_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custommatches.custommatch')),
            ],
        ),
        migrations.RenameModel(
            old_name='CstmMatchEvent',
            new_name='CustomMatchEvent',
        ),
        migrations.RenameModel(
            old_name='CstmMatchPlayerStat',
            new_name='CustomMatchPlayerStat',
        ),
        migrations.DeleteModel(
            name='CstmMatchResult',
        ),
    ]
