# Generated by Django 4.2.10 on 2024-07-13 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custommatches', '0003_custommatchresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommatchevent',
            name='custom_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='custommatches.custommatch'),
        ),
    ]
