# Generated by Django 4.2.10 on 2024-07-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custommatches', '0004_alter_custommatchevent_custom_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommatch',
            name='venue',
            field=models.CharField(max_length=20),
        ),
    ]
