# Generated by Django 4.2.10 on 2024-03-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_contract_options_remove_matchevent_player_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='player_contract',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.contract'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='playerstat',
            unique_together={('player_contract', 'match')},
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='team',
        ),
    ]
