# Generated by Django 4.2.10 on 2024-03-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_match_slug_alter_player_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('player', 'team', 'contract_date')},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('home_team', 'away_team', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='playerstat',
            unique_together={('player', 'match')},
        ),
    ]
