# Generated by Django 4.2.10 on 2024-03-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_match_date_alter_contract_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.team'),
        ),
    ]
