# Generated by Django 4.2.10 on 2024-04-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_coach_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
