# Generated by Django 4.2.10 on 2024-03-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_playerstat_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_fixture',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.team'),
        ),
    ]
