# Generated by Django 4.2.10 on 2024-04-22 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_user_is_admin_user_is_coach_user_is_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versus_team', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('is_fixture', models.BooleanField(default=True)),
                ('is_home', models.BooleanField(default=True)),
                ('user_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_matches', to='players.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.venue')),
            ],
            options={
                'unique_together': {('versus_team', 'user_team', 'date')},
            },
        ),
    ]
