# Generated by Django 4.2.10 on 2024-07-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_delete_custommatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='players.match'),
        ),
    ]
