# Generated by Django 4.2.10 on 2024-04-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_custommatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='match_date',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('home_team', 'away_team', 'match_date')},
        ),
    ]
