# Generated by Django 4.2.10 on 2024-03-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_matchevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_fixture',
        ),
    ]
