# Generated by Django 4.2.10 on 2024-07-15 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_player_user_alter_coach_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='players.team'),
        ),
    ]
