# Generated by Django 4.2.10 on 2024-03-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_match_is_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_fixture',
            field=models.BooleanField(default=True),
        ),
    ]
