# Generated by Django 4.2.10 on 2024-07-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_coach_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='role',
            field=models.CharField(default='Assistant Coach', max_length=20),
        ),
    ]
