# Generated by Django 4.2.10 on 2024-07-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_coach_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_description',
            field=models.TextField(default='No description'),
        ),
    ]
